keys:
  - &users:
    - &matthias age1jxg5c820ed2xfg96q328z624ufr6ar3hmhpyy63lmvm52yy6zc7sd0c2gm
  - &hosts:
    - &idaho age1k6lfgsaacw3cqsh86ckmwzvu8ydz29y37u5c8dqk0ath8vwfdpfsa3aclh
    - &stilgar ageTODO

creation_rules:
  - path_regex: hosts/secrets.yaml$
    key_groups:
      - age:
        - *matthias
        - *idaho
  - path_regex: hosts/stilgar/secrets.yaml$
    key_groups:
      - age:
        - *matthias
        - *stilgar
  - path_regex: home/matthias.idaho/.*secrets.yaml$
    key_groups:
      - age:
        - *matthias
        - *idaho
